---
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade installed packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - vim
    state: present