---
- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes

- name: Install Docker Compose
  apt:
    name: "{{ docker_compose_package }}"
    state: present

- name: Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Verify Docker Version
  command: docker --version
  register: docker_version

- name: Display Docker Version
  debug:
    var: docker_version.stdout