---
- name: Login to Amazon ECR
  shell: |
    aws ecr get-login-password --region {{ aws_region }} | \
    docker login \
    --username AWS \
    --password-stdin \
    {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com

- name: Pull Latest Docker Image
  docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Remove Existing Container
  docker_container:
    name: "{{ container_name }}"
    state: absent

- name: Run Application Container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ application_port }}:3000"
    env:
      PORT: "3000"