pipeline {

    agent any

    environment {

        AWS_REGION = "us-east-1"

        AWS_ACCOUNT_ID = "YOUR_AWS_ACCOUNT_ID"

        ECR_REPOSITORY = "project786"

        IMAGE_TAG = "latest"

    }

    stages {

        stage('Checkout Source') {

            steps {

                checkout scm

            }

        }

        stage('Build Docker Image') {

            steps {

                dir('docker') {

                    sh '''
                    docker build \
                    -t ${ECR_REPOSITORY}:${IMAGE_TAG} \
                    -f Dockerfile \
                    ../app
                    '''

                }

            }

        }

        stage('Login to Amazon ECR') {

            steps {

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds']
                ]) {

                    sh '''
                    aws ecr get-login-password \
                    --region ${AWS_REGION} | \
                    docker login \
                    --username AWS \
                    --password-stdin \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    '''

                }

            }

        }

        stage('Tag Docker Image') {

            steps {

                sh '''
                docker tag \
                ${ECR_REPOSITORY}:${IMAGE_TAG} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
                '''

            }

        }

        stage('Push Image to Amazon ECR') {

            steps {

                sh '''
                docker push \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
                '''

            }

        }

        stage('Deploy using Ansible') {

            steps {

                dir('ansible') {

                    sh '''
                    ansible-playbook \
                    -i inventory \
                    playbook.yml
                    '''

                }

            }

        }

    }

    post {

        always {

            cleanWs()

        }

        success {

            echo "Deployment Successful."

        }

        failure {

            echo "Deployment Failed."

        }

    }

}